# ProxyBeast by @z3ntl3
# 
# This is a CI/CD workflow to build and deploy to github releases
#
# If a PR passes the build additional reviews will be taken and it would be merged 
# when it satisfies our desires and requirements.
#
# See more of our work at simpaix.net
#
# Licensed under GNU
# - You can find the license file within the root of this directory in a file named LICENSE

name: Wails Build & Deployment
run-name: Build & Deployment triggered by ${{ github.event_name }}

on:
    pull_request:
        types: [opened, edited, reopened]
    push:
        branches: 
            - main
        tags: 
          - v*
jobs:
    build:
        runs-on: ${{ matrix.os }}
        continue-on-error: ${{ matrix.minorVer }}
        strategy:
            matrix:
                os: [windows-latest] 
                architecture: 
                  - x64
                include:
                  - version: 1.22.2
                    minorVer: false
                  - version: 1.23
                    minorVer: true
        steps:
            - name: Clone Repo
              uses: actions/checkout@v4
            
            - name: Download Go
              uses: actions/setup-go@v5
              with: 
                go-version: ${{matrix.version}}
                architecture: ${{matrix.architecture}}
              
            - name: Install Node
              uses: actions/setup-node@v4
              with: 
                architecture: ${{ matrix.architecture }}

            - name: Cache Go Dependencies / win
              id: cache-godep
              if: runner.os
              uses: actions/cache@v4
              with:
                path: |
                  ~\AppData\Local\go-build
                  ~\go\pkg\mod
                key: ${{runner.os}}-go-${{runner.arch}}

            - name: Install Go dependencies for Wails
              if: steps.cache-godep.outputs.cache-hit != 'true'
              run: |
                go get .
                go install github.com/wailsapp/wails/v2/cmd/wails@latest

            - name: Wails Doctor
              run: wails doctor
            

            # ----------------Windows
            - name: Download WINGET / windows
              if: ${{ contains(matrix.os, 'windows') }}
              uses: Cyberboss/install-winget@v1
              
            - name: Wails Build / windows
              if: ${{ contains(matrix.os, 'windows') }}
              run: wails build -nsis

            - name: Release Build / windows
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/') && contains(matrix.os, 'windows') && github.event_name == 'push'
              with:
                files: ${{github.workspace}}\build\bin\ProxyBeast.exe
                prerelease: true
                token: ${{ secrets.MY_TOKEN }} 
                name: Built for ${{':'}} ${{ matrix.os }}-${{matrix.architecture}}
                body: |
                  This executable is deployed automatically.

                  - Ref: ${{github.ref}}
            # -----------------------------Windows


         
