# ProxyBeast by @z3ntl3
# 
# This is a workflow to test CI/CD to build and deploy to github releases
#
# See more of our work at simpaix.net
#
# Licensed under GNU
# - You can find the license file within the root of this directory in a file named LICENSE

name: Wails Build & Deployment
run-name: Build & Deployment triggered by ${{github.event_name}}

on:
    pull_request:
        types: [opened, edited, reopened]
    push:
        branches: 
            - main
        tags: 
          - v*
jobs:
    build:
        continue-on-error: true
        strategy:
            matrix:
                version: [1.23]
                os: [macos-latest] # [windows-latest, macos-latest] currently only windows support for proxybeast
                architecture: 
                  - x64

        runs-on: ${{ matrix.os }}
        steps:
            - name: Clone Repo
              uses: actions/checkout@v4
            
            - name: Download Go
              uses: actions/setup-go@v5
              with: 
                go-version: ${{matrix.version}}
                architecture: ${{matrix.architecture}}
              
            - name: Install Node
              uses: actions/setup-node@v4
              with: 
                architecture: ${{ matrix.architecture }}

            - name: Cache Go Dependencies / win
              id: cache-godep
              if: runner.os
              uses: actions/cache@v4
              with:
                path: |
                  ~\AppData\Local\go-build
                  ~\go\pkg\mod
                key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

            - name: Install Go dependencies for Wails
              if: steps.cache-godep.outputs.cache-hit != 'true'
              run: |
                go get .
                go install github.com/wailsapp/wails/v2/cmd/wails@latest
            

            - name: Wails Doctor
              run: wails doctor
            
            # -----------------Macos & Linux
            - name: Wails Build / mac-os & linux
              if: ${{ ! contains(matrix.os, 'windows') }}
              run: |
               wails build

            - name: Release Build / macos
              if: startsWith(github.ref, 'refs/tags/') && contains(matrix.os, 'macos') && github.event_name == 'push'
              uses: softprops/action-gh-release@v2
              with:
                files: |
                 ${{github.workspace}}/build/bin/**/*.app
                 ${{github.workspace}}/build/bin/*.app

                prerelease: true
                token: ${{ secrets.MY_TOKEN }} 

            - name: Release Build / linux
              if: startsWith(github.ref, 'refs/tags/') && contains(matrix.os, 'ubuntu') && github.event_name == 'push'
              uses: softprops/action-gh-release@v2
              with:
                files: ${{github.workspace}}/build/bin/ProxyBeast
                prerelease: true
                token: ${{ secrets.MY_TOKEN }} 
            # ------------------Macos & Linux

            # ----------------Windows
            - name: Download WINGET / windows
              if: ${{ contains(matrix.os, 'windows') }}
              uses: Cyberboss/install-winget@v1
              
            - name: Wails Build / windows
              if: ${{ contains(matrix.os, 'windows') }}
              run: wails build -nsis

            - name: Release Build / windows
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/') && contains(matrix.os, 'windows') && github.event_name == 'push'
              with:
                files: ${{github.workspace}}\build\bin\ProxyBeast.exe
                prerelease: true
                token: ${{ secrets.MY_TOKEN }} 
            # -----------------------------Windows


         
